#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_user
    username: root
    password: "@root1234"


mybatis-plus:
  mapper-locations: classpath:com.self.manager.mapper.xml/*.xml
  type-aliases-package: com.self.manager.entity
